### PR TITLE
Added .NET Core 1.0 support

### PR DESCRIPTION
**Pull request by daghb**
Added project.json for this project along with an updated .gitignore for project.lock.json.

### CODE REVIEW

**Comment by sonicjolt** [comment]
I can't seem to get this to work. Can you make a test build on appveyor and retry please

**Comment by jaredcnance** [comment]
What was the issue here? Need any assistance?

**Comment by daghb** [comment]
I didn't notice the Appveyor build. Having tested that now, I guess the best thing to do here, is forking the code and create a separate project for .NET Core.

**Comment by jaredcnance** [comment]
See #27, let me know if this works for you

**Pull request merged**
